### PR TITLE
add chat hint and indicator of unread messages

### PR DESCRIPTION
**Pull request by ZXb125**

### CODE REVIEW

**Comment by bgkillas** [comment]
can you post images when you do ui changes?

**Comment by ZXb125** [comment]
image
sure, here is the one of that change, bottom left

**Comment by bgkillas** [comment]
can you add an option to disable this? im fine with it being enabled by default but i feel like id rather not see it in larger lobbys

**Comment by ZXb125** [comment]
that ui text only appears when you have unread messages but sure I will try to do that

**Pull request merged**
